export const CHANGE_WEBITEM = 'CHANGE_WEBITEM'

export const CHANGE_TITLE = 'CHANGE_TITLE'

export const CHANGE_ISLOAD = 'CHANGE_ISLOAD'

export const CHANGE_ROTATEDEG = 'CHANGE_ROTATEDEG'

export const CHANGE_KEYWORDS = 'CHANGE_KEYWORDS'

export const CHANGE_SEARCHTYPE = 'CHANGE_SEARCHTYPE'

export const GETSEARCHONE = 'GETSEARCHONE'

export const GETSEARCHDT = 'GETSEARCHDT'

export const GETSEARCHEIGHT = 'GETSEARCHEIGHT'

export const INIT_SEARCHDATA = 'INIT_SEARCHDATA'
